In [3]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/aabdollahii/humanvsai/HVA-Grok-GPT-Qwen.xlsx
/kaggle/input/datasets/aabdollahii/humanvsai/dataset (1).xlsx
/kaggle/input/datasets/aabdollahii/humanvsai/HVA-Qewn-only.csv

In [4]:
import pandas as pd

path = "/kaggle/input/datasets/aabdollahii/humanvsai/HVA-Grok-GPT-Qwen.xlsx"
df = pd.read_excel(path)

print(df.shape)
print(df.columns.tolist())
print(df.dtypes)
df.head(10)

(1519, 8)
['year', 'filename', 'text', 'word_count', 'label', 'MODEL1', 'MODEL2', 'MODEL3']
year           int64
filename      object
text          object
word_count     int64
label         object
MODEL1        object
MODEL2        object
MODEL3        object
dtype: object

,year,filename,text,word_count,label,MODEL1,MODEL2,MODEL3
0,2003,HAM2-811011-027.ham,آغاز ساخت بدنه و سرريز بلندترين سد\nكشور\nعملي...,136,human,آغاز فازهای کلیدی ساخت بزرگ‌ترین سازه آبی کشور...,عملیات اجرایی بدنه و سرریز سد کارون ۴ که بلندت...,آغاز عملیات اجرایی سد جدید بر روی رودخانه کارو...
1,2003,HAM2-811014-088.ham,گزارش حجم آب مفيد سدهاي تامين كننده آب\nشرب ته...,53,human,وضعیت ذخایر آبی سدهای استراتژیک استان تهران که...,حجم آب مفید سدهای تأمین‌کننده آب شرب تهران بر ...,گزارش تازه آب ذخیره شده در سدهای تهران نشان می...
2,2003,HAM2-811015-093.ham,كفاشيان: هر نامزدي به روند انتخابات \nاعتراض د...,138,human,در فضای پرچالش ورزش کشور، تنش‌های вокруг انتخا...,سرپرست فدراسیون دو و میدانی از تغییر زمان برگز...,کفاشیان: زمان انتخابات را مرجع قانونی تعیین می...
3,2003,HAM2-811015-094.ham,دعوت شدگان جديد در اردوي تيم واليبال \nجوانان ...,122,human,تیم والیبال جوانان ایران در آستانه حضور در رقا...,در پایان دور رفت مسابقات والیبال قهرمانی جوانا...,پانزده بازیکن تازه به اردوی تیم والیبال جوانان...
4,2003,HAM2-811016-002.ham,نمايش آثار هنري دهه 40و50 جمهوري چك\nآثار هنري...,181,human,نمايشگاهي جديد در موزه شهر لونسدُن، موزه‌ای اس...,آثار هنری دوره استیلای رژیم کمونیستی در دهه‌ها...,نمایشگاه هنرهای رسمی چک در سال های حاکمیت کمون...
5,2003,HAM2-811017-031.ham,نخستين همايش ملي ميراث فرهنگي و نسل \nسوم برگز...,134,human,دومین همایش ملی میراث فرهنگی و نسل جوان با حضو...,نخستین همایش ملی میراث فرهنگی و نسل سوم ۱۹ دی ...,همایش ملی میراث فرهنگی و جوانان برگزار می شود ...
6,2003,HAM2-811018-027.ham,مجوز داير شدن رشته هاي فني و حرفه اي به \nاستا...,169,human,سیاست‌های جدید وزارت آموزش و پرورش با هدف ارتق...,مدیرکل دفتر آموزش فنی و حرفه‌ای وزارت آموزش و ...,اختیار ایجاد رشته های هنرستانی به استان ها واگ...
7,2003,HAM2-811018-029.ham,آثار و ابنيه تپه باستاني هگمتانه \nرديابي شد\n...,189,human,تپه باستانی هگمتانه در همدان، که به عنوان یکی ...,برای نخستین بار در تپه باستانی هگمتانه مطالعات...,بررسی های ژئوفیزیکی تازه در تپه باستانی هگمتان...
8,2003,HAM2-811019-122.ham,بسكتبال با ويلچر قهرماني ايران در گام آخر مقدم...,99,human,همزمان با نزدیک شدن به مرحله نهایی رقابت‌ها، ه...,هفته پایانی مرحله مقدماتی مسابقات بسکتبال با و...,هفته پایانی مرحله مقدماتی بسکتبال با ویلچر در ...
9,2003,HAM2-811021-040.ham,احتمال تشكيل جلسه فوق العاده اوپك\nگروه اقتصاد...,121,human,بر اساس گزارش‌های اخیر منتشر شده از سوی شبکه خ...,شبکه خبری داوجونز اعلام کرد اعضای اوپک به احتم...,اوپک برای بررسی افزایش تولید تشکیل جلسه می دهد...

In [5]:
model_map = {"text": "human", "MODEL1": "qwen", "MODEL2": "grok", "MODEL3": "gpt"}

long_df = df.melt(
    id_vars=["year", "filename", "word_count"],
    value_vars=list(model_map.keys()),
    var_name="source_col",
    value_name="content",
)

long_df["source"] = long_df["source_col"].map(model_map)
long_df["label"] = (long_df["source"] != "human").astype(int)   # 0 = human, 1 = machine
long_df = long_df.drop(columns=["source_col"]).dropna(subset=["content"])
long_df["content"] = long_df["content"].astype(str).str.strip()
long_df["n_words"] = long_df["content"].str.split().str.len()

long_df = long_df.sort_values(["filename", "source"]).reset_index(drop=True)

print(long_df.shape)
print(long_df["source"].value_counts())
long_df.head(12)

(5647, 7)
source
grok     1519
human    1519
qwen     1519
gpt      1090
Name: count, dtype: int64

,year,filename,word_count,content,source,label,n_words
0,2003,HAM2-811011-027.ham,136,آغاز عملیات اجرایی سد جدید بر روی رودخانه کارو...,gpt,1,105
1,2003,HAM2-811011-027.ham,136,عملیات اجرایی بدنه و سرریز سد کارون ۴ که بلندت...,grok,1,93
2,2003,HAM2-811011-027.ham,136,آغاز ساخت بدنه و سرريز بلندترين سد\nكشور\nعملي...,human,0,143
3,2003,HAM2-811011-027.ham,136,آغاز فازهای کلیدی ساخت بزرگ‌ترین سازه آبی کشور...,qwen,1,210
4,2003,HAM2-811014-088.ham,53,گزارش تازه آب ذخیره شده در سدهای تهران نشان می...,gpt,1,103
5,2003,HAM2-811014-088.ham,53,حجم آب مفید سدهای تأمین‌کننده آب شرب تهران بر ...,grok,1,85
6,2003,HAM2-811014-088.ham,53,گزارش حجم آب مفيد سدهاي تامين كننده آب\nشرب ته...,human,0,69
7,2003,HAM2-811014-088.ham,53,وضعیت ذخایر آبی سدهای استراتژیک استان تهران که...,qwen,1,180
8,2003,HAM2-811015-093.ham,138,کفاشیان: زمان انتخابات را مرجع قانونی تعیین می...,gpt,1,100
9,2003,HAM2-811015-093.ham,138,سرپرست فدراسیون دو و میدانی از تغییر زمان برگز...,grok,1,83
10,2003,HAM2-811015-093.ham,138,كفاشيان: هر نامزدي به روند انتخابات \nاعتراض د...,human,0,138
11,2003,HAM2-811015-093.ham,138,در فضای پرچالش ورزش کشور، تنش‌های вокруг انتخا...,qwen,1,178