<a href="https://www.kaggle.com/code/aabdollahii/8-ml-solution-final-data-analysis?scriptVersionId=339105278" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/aabdollahii/humanvsai/HVA-Grok-GPT-Qwen.xlsx
/kaggle/input/datasets/aabdollahii/humanvsai/dataset (1).xlsx
/kaggle/input/datasets/aabdollahii/humanvsai/HVA-Qewn-only.csv
/kaggle/input/pm-129186164-at-07-30-2026-16-18-24/__script__.py
/kaggle/input/pm-129186164-at-07-30-2026-16-18-24/tqdm-4.70.0-py3-none-any.whl
/kaggle/input/pm-129186164-at-07-30-2026-16-18-24/httpx-0.28.1-py3-none-any.whl
/kaggle/input/pm-129186164-at-07-30-2026-16-18-24/h11-0.16.0-py3-none-any.whl
/kaggle/input/pm-129186164-at-07-30-2026-16-18-24/httpcore-1.0.9-py3-none-any.whl
/kaggle/input/pm-129186164-at-07-30-2026-16-18-24/hazm-0.12.1-py3-none-any.whl
/kaggle/input/pm-129186164-at-07-30-2026-16-18-24/idna-3.18-py3-none-any.whl
/kaggle/input/pm-129186164-at-07-30-2026-16-18-24/click-8.4.2-py3-none-any.whl
/kaggle/input/pm-129186164-at-07-30-2026-16-18-24/python_crfsuite-0.9.12-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl
/kaggle/input/pm-129186164-at-07-30-2026-16-18-24/hf_xet-1.5.2-cp38-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl
/kaggle/input/pm-129186164-at-07-30-2026-16-18-24/__results__.html
/kaggle/input/pm-129186164-at-07-30-2026-16-18-24/typing_extensions-4.16.0-py3-none-any.whl
/kaggle/input/pm-129186164-at-07-30-2026-16-18-24/input_requirements.txt
/kaggle/input/pm-129186164-at-07-30-2026-16-18-24/regex-2026.7.19-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl
/kaggle/input/pm-129186164-at-07-30-2026-16-18-24/certifi-2026.7.22-py3-none-any.whl
/kaggle/input/pm-129186164-at-07-30-2026-16-18-24/defusedxml-0.7.1-py2.py3-none-any.whl
/kaggle/input/pm-129186164-at-07-30-2026-16-18-24/__script__.ipynb
/kaggle/input/pm-129186164-at-07-30-2026-16-18-24/fsspec-2026.7.0-py3-none-any.whl
/kaggle/input/pm-129186164-at-07-30-2026-16-18-24/__output__.json
/kaggle/input/pm-129186164-at-07-30-2026-16-18-24/anyio-4.14.2-py3-none-any.whl
/kaggle/input/pm-129186164-at-07-30-2026-16-18-24/pyyaml-6.0.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl
/kaggle/input/pm-129186164-at-07-30-2026-16-18-24/joblib-1.5.3-py3-none-any.whl
/kaggle/input/pm-129186164-at-07-30-2026-16-18-24/huggingface_hub-1.26.0-py3-none-any.whl
/kaggle/input/pm-129186164-at-07-30-2026-16-18-24/packaging-26.2-py3-none-any.whl
/kaggle/input/pm-129186164-at-07-30-2026-16-18-24/nltk-3.10.0-py3-none-any.whl
/kaggle/input/pm-129186164-at-07-30-2026-16-18-24/filelock-3.32.2-py3-none-any.whl
/kaggle/input/pm-129186164-at-07-30-2026-16-18-24/install_requirements.sh
/kaggle/input/pm-129186164-at-07-30-2026-16-18-24/flashtext-2.7.tar.gz
/kaggle/input/pm-129186164-at-07-30-2026-16-18-24/custom.css

In [2]:
import pandas as pd

path = "/kaggle/input/datasets/aabdollahii/humanvsai/HVA-Grok-GPT-Qwen.xlsx"
df = pd.read_excel(path)

print(df.shape)
print(df.columns.tolist())
print(df.dtypes)
df.head(10)

(1519, 8)
['year', 'filename', 'text', 'word_count', 'label', 'MODEL1', 'MODEL2', 'MODEL3']
year           int64
filename      object
text          object
word_count     int64
label         object
MODEL1        object
MODEL2        object
MODEL3        object
dtype: object

,year,filename,text,word_count,label,MODEL1,MODEL2,MODEL3
0,2003,HAM2-811011-027.ham,آغاز ساخت بدنه و سرريز بلندترين سد\nكشور\nعملي...,136,human,آغاز فازهای کلیدی ساخت بزرگ‌ترین سازه آبی کشور...,عملیات اجرایی بدنه و سرریز سد کارون ۴ که بلندت...,آغاز عملیات اجرایی سد جدید بر روی رودخانه کارو...
1,2003,HAM2-811014-088.ham,گزارش حجم آب مفيد سدهاي تامين كننده آب\nشرب ته...,53,human,وضعیت ذخایر آبی سدهای استراتژیک استان تهران که...,حجم آب مفید سدهای تأمین‌کننده آب شرب تهران بر ...,گزارش تازه آب ذخیره شده در سدهای تهران نشان می...
2,2003,HAM2-811015-093.ham,كفاشيان: هر نامزدي به روند انتخابات \nاعتراض د...,138,human,در فضای پرچالش ورزش کشور، تنش‌های вокруг انتخا...,سرپرست فدراسیون دو و میدانی از تغییر زمان برگز...,کفاشیان: زمان انتخابات را مرجع قانونی تعیین می...
3,2003,HAM2-811015-094.ham,دعوت شدگان جديد در اردوي تيم واليبال \nجوانان ...,122,human,تیم والیبال جوانان ایران در آستانه حضور در رقا...,در پایان دور رفت مسابقات والیبال قهرمانی جوانا...,پانزده بازیکن تازه به اردوی تیم والیبال جوانان...
4,2003,HAM2-811016-002.ham,نمايش آثار هنري دهه 40و50 جمهوري چك\nآثار هنري...,181,human,نمايشگاهي جديد در موزه شهر لونسدُن، موزه‌ای اس...,آثار هنری دوره استیلای رژیم کمونیستی در دهه‌ها...,نمایشگاه هنرهای رسمی چک در سال های حاکمیت کمون...
5,2003,HAM2-811017-031.ham,نخستين همايش ملي ميراث فرهنگي و نسل \nسوم برگز...,134,human,دومین همایش ملی میراث فرهنگی و نسل جوان با حضو...,نخستین همایش ملی میراث فرهنگی و نسل سوم ۱۹ دی ...,همایش ملی میراث فرهنگی و جوانان برگزار می شود ...
6,2003,HAM2-811018-027.ham,مجوز داير شدن رشته هاي فني و حرفه اي به \nاستا...,169,human,سیاست‌های جدید وزارت آموزش و پرورش با هدف ارتق...,مدیرکل دفتر آموزش فنی و حرفه‌ای وزارت آموزش و ...,اختیار ایجاد رشته های هنرستانی به استان ها واگ...
7,2003,HAM2-811018-029.ham,آثار و ابنيه تپه باستاني هگمتانه \nرديابي شد\n...,189,human,تپه باستانی هگمتانه در همدان، که به عنوان یکی ...,برای نخستین بار در تپه باستانی هگمتانه مطالعات...,بررسی های ژئوفیزیکی تازه در تپه باستانی هگمتان...
8,2003,HAM2-811019-122.ham,بسكتبال با ويلچر قهرماني ايران در گام آخر مقدم...,99,human,همزمان با نزدیک شدن به مرحله نهایی رقابت‌ها، ه...,هفته پایانی مرحله مقدماتی مسابقات بسکتبال با و...,هفته پایانی مرحله مقدماتی بسکتبال با ویلچر در ...
9,2003,HAM2-811021-040.ham,احتمال تشكيل جلسه فوق العاده اوپك\nگروه اقتصاد...,121,human,بر اساس گزارش‌های اخیر منتشر شده از سوی شبکه خ...,شبکه خبری داوجونز اعلام کرد اعضای اوپک به احتم...,اوپک برای بررسی افزایش تولید تشکیل جلسه می دهد...

In [3]:
model_map = {"text": "human", "MODEL1": "qwen", "MODEL2": "grok", "MODEL3": "gpt"}

long_df = df.melt(
    id_vars=["year", "filename", "word_count"],
    value_vars=list(model_map.keys()),
    var_name="source_col",
    value_name="content",
)

long_df["source"] = long_df["source_col"].map(model_map)
long_df["label"] = (long_df["source"] != "human").astype(int)   # 0 = human, 1 = machine
long_df = long_df.drop(columns=["source_col"]).dropna(subset=["content"])
long_df["content"] = long_df["content"].astype(str).str.strip()
long_df["n_words"] = long_df["content"].str.split().str.len()

long_df = long_df.sort_values(["filename", "source"]).reset_index(drop=True)

print(long_df.shape)
print(long_df["source"].value_counts())
long_df.head(12)

(5647, 7)
source
grok     1519
human    1519
qwen     1519
gpt      1090
Name: count, dtype: int64

,year,filename,word_count,content,source,label,n_words
0,2003,HAM2-811011-027.ham,136,آغاز عملیات اجرایی سد جدید بر روی رودخانه کارو...,gpt,1,105
1,2003,HAM2-811011-027.ham,136,عملیات اجرایی بدنه و سرریز سد کارون ۴ که بلندت...,grok,1,93
2,2003,HAM2-811011-027.ham,136,آغاز ساخت بدنه و سرريز بلندترين سد\nكشور\nعملي...,human,0,143
3,2003,HAM2-811011-027.ham,136,آغاز فازهای کلیدی ساخت بزرگ‌ترین سازه آبی کشور...,qwen,1,210
4,2003,HAM2-811014-088.ham,53,گزارش تازه آب ذخیره شده در سدهای تهران نشان می...,gpt,1,103
5,2003,HAM2-811014-088.ham,53,حجم آب مفید سدهای تأمین‌کننده آب شرب تهران بر ...,grok,1,85
6,2003,HAM2-811014-088.ham,53,گزارش حجم آب مفيد سدهاي تامين كننده آب\nشرب ته...,human,0,69
7,2003,HAM2-811014-088.ham,53,وضعیت ذخایر آبی سدهای استراتژیک استان تهران که...,qwen,1,180
8,2003,HAM2-811015-093.ham,138,کفاشیان: زمان انتخابات را مرجع قانونی تعیین می...,gpt,1,100
9,2003,HAM2-811015-093.ham,138,سرپرست فدراسیون دو و میدانی از تغییر زمان برگز...,grok,1,83
10,2003,HAM2-811015-093.ham,138,كفاشيان: هر نامزدي به روند انتخابات \nاعتراض د...,human,0,138
11,2003,HAM2-811015-093.ham,138,در فضای پرچالش ورزش کشور، تنش‌های вокруг انتخا...,qwen,1,178

In [4]:
import pandas as pd
import re
from hazm import Normalizer

# Load your dataset
path = "/kaggle/input/datasets/aabdollahii/humanvsai/HVA-Grok-GPT-Qwen.xlsx"
df = pd.read_excel(path)

# Initialize Hazm Normalizer
normalizer = Normalizer()

def preprocess_persian_text(text):
    if not isinstance(text, str):
        return ""
    
    # 1. Remove newlines and excess whitespace
    text = text.replace('\n', ' ').replace('\r', ' ')
    text = re.sub(r'\s+', ' ', text).strip()
    
    # 2. Normalize using Hazm (handles Persian characters, alef/ye/ke standardization)
    text = normalizer.normalize(text)
    
    # 3. Convert all English digits to Persian digits
    english_to_persian = {
        '0': '۰', '1': '۱', '2': '۲', '3': '۳', '4': '۴',
        '5': '۵', '6': '۶', '7': '۷', '8': '۸', '9': '۹'
    }
    for eng, per in english_to_persian.items():
        text = text.replace(eng, per)
        
    return text

text_column_name = 'text' 
if text_column_name in df.columns:
    df[text_column_name] = df[text_column_name].apply(preprocess_persian_text)

# Save to output directory in Kaggle
output_path = "/kaggle/working/cleaned_HVA_dataset.xlsx"
df.to_excel(output_path, index=False)

print(f"Preprocessing complete. Saved to: {output_path}")
print(df.head(5))

Preprocessing complete. Saved to: /kaggle/working/cleaned_HVA_dataset.xlsx
   year             filename  \
0  2003  HAM2-811011-027.ham
1  2003  HAM2-811014-088.ham
2  2003  HAM2-811015-093.ham
3  2003  HAM2-811015-094.ham
4  2003  HAM2-811016-002.ham

                                                text  word_count  label  \
0  آغاز ساخت بدنه و سرریز بلندترین سد کشور عملیات...         136  human
1  گزارش حجم آب مفید سدهای تامین کننده آب شرب تهر...          53  human
2  کفاشیان: هر نامزدی به روند انتخابات اعتراض دار...         138  human
3  دعوت شدگان جدید در اردوی تیم والیبال جوانان ای...         122  human
4  نمایش آثار هنری دهه ۴۰ و ۵۰ جمهوری چک آثار هنر...         181  human

                                              MODEL1  \
0  آغاز فازهای کلیدی ساخت بزرگ‌ترین سازه آبی کشور...
1  وضعیت ذخایر آبی سدهای استراتژیک استان تهران که...
2  در فضای پرچالش ورزش کشور، تنش‌های вокруг انتخا...
3  تیم والیبال جوانان ایران در آستانه حضور در رقا...
4  نمايشگاهي جديد در موزه شهر لونسدُن، موزه‌ای اس...

                                              MODEL2  \
0  عملیات اجرایی بدنه و سرریز سد کارون ۴ که بلندت...
1  حجم آب مفید سدهای تأمین‌کننده آب شرب تهران بر ...
2  سرپرست فدراسیون دو و میدانی از تغییر زمان برگز...
3  در پایان دور رفت مسابقات والیبال قهرمانی جوانا...
4  آثار هنری دوره استیلای رژیم کمونیستی در دهه‌ها...

                                              MODEL3
0  آغاز عملیات اجرایی سد جدید بر روی رودخانه کارو...
1  گزارش تازه آب ذخیره شده در سدهای تهران نشان می...
2  کفاشیان: زمان انتخابات را مرجع قانونی تعیین می...
3  پانزده بازیکن تازه به اردوی تیم والیبال جوانان...
4  نمایشگاه هنرهای رسمی چک در سال های حاکمیت کمون...

# long version

In [5]:

normalizer = Normalizer()

digit_map = str.maketrans({
    "0": "۰", "1": "۱", "2": "۲", "3": "۳", "4": "۴",
    "5": "۵", "6": "۶", "7": "۷", "8": "۸", "9": "۹",
    "٠": "۰", "١": "۱", "٢": "۲", "٣": "۳", "٤": "۴",
    "٥": "۵", "٦": "۶", "٧": "۷", "٨": "۸", "٩": "۹",
})

def preprocess_persian_text(text):
    if pd.isna(text):
        return ""

    text = str(text)

    # Remove newline-like leakage characters
    text = text.replace("\n", " ")
    text = text.replace("\r", " ")
    text = text.replace("\t", " ")
    text = text.replace("\v", " ")
    text = text.replace("\f", " ")

    # Remove escaped newline forms if they exist as literal text
    text = text.replace("\\n", " ")
    text = text.replace("\\r", " ")
    text = text.replace("\\t", " ")

    # Remove HTML/XML tags if present
    text = re.sub(r"<[^>]+>", " ", text)

    # Normalize Persian text with Hazm
    text = normalizer.normalize(text)

    # Convert Arabic/Persian variants and invisible spacing issues
    text = text.replace("ك", "ک")
    text = text.replace("ي", "ی")
    text = text.replace("ى", "ی")
    text = text.replace("ة", "ه")
    text = text.replace("ؤ", "و")
    text = text.replace("إ", "ا")
    text = text.replace("أ", "ا")
    text = text.replace("ٱ", "ا")

    # Remove Arabic diacritics
    text = re.sub(r"[\u064B-\u065F\u0670\u06D6-\u06ED]", "", text)

    # Convert all digits to Persian digits
    text = text.translate(digit_map)

    # Remove repeated whitespace again after normalization
    text = re.sub(r"\s+", " ", text).strip()

    return text


# Apply preprocessing to the long-format dataframe
long_df["content"] = long_df["content"].apply(preprocess_persian_text)

# Remove empty rows after cleaning
long_df = long_df[long_df["content"].str.len() > 0].reset_index(drop=True)

# Recalculate simple word count after cleaning, without tokenization
long_df["n_words"] = long_df["content"].str.split().str.len()

# Save cleaned long-format dataset to Kaggle output
output_xlsx = "/kaggle/working/HVA_long_preprocessed.xlsx"
output_csv = "/kaggle/working/HVA_long_preprocessed.csv"

long_df.to_excel(output_xlsx, index=False)
long_df.to_csv(output_csv, index=False, encoding="utf-8-sig")

print("Saved Excel:", output_xlsx)
print("Saved CSV:", output_csv)
print(long_df.shape)
print(long_df["source"].value_counts())
long_df.head(12)

Saved Excel: /kaggle/working/HVA_long_preprocessed.xlsx
Saved CSV: /kaggle/working/HVA_long_preprocessed.csv
(5647, 7)
source
grok     1519
human    1519
qwen     1519
gpt      1090
Name: count, dtype: int64

,year,filename,word_count,content,source,label,n_words
0,2003,HAM2-811011-027.ham,136,آغاز عملیات اجرایی سد جدید بر روی رودخانه کارو...,gpt,1,96
1,2003,HAM2-811011-027.ham,136,عملیات اجرایی بدنه و سرریز سد کارون ۴ که بلندت...,grok,1,92
2,2003,HAM2-811011-027.ham,136,آغاز ساخت بدنه و سرریز بلندترین سد کشور عملیات...,human,0,137
3,2003,HAM2-811011-027.ham,136,آغاز فازهای کلیدی ساخت بزرگ‌ترین سازه آبی کشور...,qwen,1,209
4,2003,HAM2-811014-088.ham,53,گزارش تازه آب ذخیره‌شده در سدهای تهران نشان می...,gpt,1,92
5,2003,HAM2-811014-088.ham,53,حجم آب مفید سدهای تامین‌کننده آب شرب تهران بر ...,grok,1,99
6,2003,HAM2-811014-088.ham,53,گزارش حجم آب مفید سدهای تامین کننده آب شرب تهر...,human,0,78
7,2003,HAM2-811014-088.ham,53,وضعیت ذخایر آبی سدهای استراتژیک استان تهران که...,qwen,1,178
8,2003,HAM2-811015-093.ham,138,کفاشیان: زمان انتخابات را مرجع قانونی تعیین می...,gpt,1,95
9,2003,HAM2-811015-093.ham,138,سرپرست فدراسیون دو و می‌دانی از تغییر زمان برگ...,grok,1,83
10,2003,HAM2-811015-093.ham,138,کفاشیان: هر نامزدی به روند انتخابات اعتراض دار...,human,0,137
11,2003,HAM2-811015-093.ham,138,در فضای پرچالش ورزش کشور، تنش‌های вокруг انتخا...,qwen,1,178